name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # You can also add pull_request or other triggers.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check out
        uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages       # The branch to deploy to
          folder: build          # The folder to deploy
          clean: true            # Optional: remove existing files on gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}  # Auth token